name: PlatformTests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_test:
    name: Unit test

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1"
          check-latest: true

      - name: Run unit test
        run: |
          go mod download
          go test -race -v ./...

  testFreeBSD:
    runs-on: macos-12
    name: Unit test (freebsd, 1.18)
    steps:
      - uses: actions/checkout@v3
      - name: test (freebsd, 1.18)
        id: test
        uses: vmactions/freebsd-vm@v0.2.0
        with:
          usesh: true
          prepare: pkg install -y go
          run: |
            pw user add -n action -m
            su action -c 'go test -race ./...'

  testOpenBSD:
    runs-on: macos-12
    name: Unit test (openbsd, 1.18)
    steps:
      - uses: actions/checkout@v3
      - name: test (openbsd, 1.18)
        id: test
        uses: vmactions/openbsd-vm@v0.0.6
        with:
          prepare: pkg_add go
          run: |
            useradd -mG wheel action
            su action -c 'go test ./...'

  testNetBSD:
    runs-on: macos-12
    name: Unit test (netbsd, 1.18)
    steps:
      - uses: actions/checkout@v3
      - name: test (netbsd, 1.18)
        id: test
        uses: vmactions/netbsd-vm@v0.0.4
        with:
          prepare: pkg_add go
          run: |
            useradd -mG wheel action
            su action -c 'go118 test ./...'

  testillumos:
    runs-on: macos-12
    name: Unit test (illumos, 1.18)
    steps:
      - uses: actions/checkout@v2
      - name: test (illumos, 1.18)
        id: test
        uses: papertigers/illumos-vm@r38
        with:
          prepare: |
            pkg install go-118
          run: |
            useradd action
            export GOCACHE=/tmp/go-cache
            export GOPATH=/tmp/go-path
            su action -c '/opt/ooce/go-1.18/bin/go test ./...'
